apiVersion: apps/v1
kind: Deployment
metadata:
  name: hal-components
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hal-components
      microservice-type: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hal-components
        microservice-type: webapp
    spec:
      dnsConfig:
        options:
          - name: single-request-reopen
      containers:
      - name: hal-components
        image: containerregistryprod.azurecr.io/hal-components:imagetag
        resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: containerregistryprodsecret
---
kind: Service
apiVersion: v1
metadata:
  name: hal-components
spec:
  selector:
    app: hal-components
    microservice-type: webapp
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hal-components
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: hal-components.hafslundnett.io
    http: 
      paths:
      - path: /
        backend:
          serviceName: hal-components
          servicePort: 80