name: Node CI

on: [push]

jobs:
  build:
    name: Run test, lint and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
       
    - name: Install
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: yarn
    
    - name: Test
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn ci
  
